name: 'Chromatic'

on:
  push:
    paths:
      - 'packages/ui/**'
      - '.github/workflows/chromatic.yaml'

defaults:
  run:
    working-directory: ./packages/ui

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install asdf plugins and tools
        uses: asdf-vm/actions/install@v1

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: true
          # chromatic action ignores global working directory, so to set again here
          # source: https://github.com/chromaui/chromatic-cli/pull/212
          workingDir: ./packages/ui